language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
    - libusb-1.0
    - libusb-dev
before_script:
  - rustup component add clippy
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test