[workspace]
members = [
    "cli",
    "debugger",
    "gdb-server",
    "probe-rs",
    "probe-rs-target",
    "probe-rs-cli-util",
    "rtt",
    "rtthost",
    "smoke-tester",
    "xtask",
    "target-gen",
]
