[package]
name = "cli"
version = "0.1.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>"]
edition = "2018"

[dependencies]
libusb = "0.3.0"
structopt = "0.2.14"
memory = { path = "../memory" }
probe = { path = "../probe" }
stlink = { path = "../probe/stlink" }
daplink = { path = "../probe/daplink" }
coresight = { path = "../coresight" }
scroll = "*"