[package]
name = "probe"
version = "0.1.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>"]
edition = "2018"

[dependencies]
memory = { path = "../memory" }
coresight = { path = "../coresight"}
query_interface = "*"
log = "0.4.6"
bitfield = "*"
ihex = "1.1.2"
scroll = "*"
serde = "1.0.99"
