[package]
name = "probe"
version = "0.1.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>"]
edition = "2018"

[dependencies]
memory = { path = "../memory" }
coresight = { path = "../coresight"}
query_interface = "*"