[package]
name = "daplink"
version = "0.1.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>", "Dominik Boehi <dominik.boehi@gmail.ch>"]
edition = "2018"
description = "A driver to communicate with any daplink debug adapter."
documentation = "https://docs.rs/daplink/"
homepage = "https://github.com/probe-rs/probe-rs/daplink"
repository = "https://github.com/probe-rs/probe-rs/daplink"
readme = "../../README.md"
categories = ["embedded", "hardware-support", "development-tools::debugging"]
keywords = ["embedded"]
license = "MIT OR Apache-2.0"

[dependencies]
log = "0.4.6"
lazy_static = "1.2.0"
probe = { path = "../", version = "0.1.0" }
arm-memory = { path = "../../memory", version = "0.1.0" }
coresight = { path = "../../coresight", version = "0.1.0"}
scroll = "0.9.2"
rental = "0.5.4"
hidapi = "0.5.2"