[package]
name = "stlink"
version = "0.1.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>"]
edition = "2018"

[dependencies]
rusb = "0.5.1"
lazy_static = "1.2.0"
probe = { path = "../" }
memory = { path = "../../memory" }
coresight = { path = "../../coresight" }
scroll = "*"
rental = "*"