# This Action is triggered when a PR with the label 'release' is created against 'master'.
# It checks if the crates in the repo could publish to crates.io.

on:
  pull_request:
    branches: [master]

name: Check that the release on crates.io will succeed.

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.names, 'release') }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install libusb and libftdi (linux)
        run: |
          sudo apt update
          sudo apt install -y libusb-dev libusb-1.0 libftdi1-dev

      - name: Install Rust toolchains
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - uses: katyo/publish-crates@v1
        with:
            dry-run: true