# This Action is triggered when a PR with the label 'release' is closed and merged into 'master'.
# It publishes the crates in the repo to crates.io.

on:
  pull_request:
    branches: [master]
    types: [closed]

name: Release on crates.io

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.names, 'release')

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install libusb and libftdi (linux)
        run: |
          sudo apt update
          sudo apt install -y libusb-dev libusb-1.0 libftdi1-dev

      - name: Install Rust toolchains
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Publish to crates.io
        uses: katyo/publish-crates@v1
        with:
            registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}